assert_lefthook_installed: true

pre-commit:
  parallel: true
  commands:
    fmt:
      run: bun dprint fmt
      staged_fixed: true
    lint:
      run: bun biome lint --config-path=.biome.jsonc --no-errors-on-unmatched
