assert_lefthook_installed: true
output: [execution, failure, summary]
pre-commit:
  parallel: true
  commands:
    fmt:
      run: bun dprint fmt
      stage_fixed: true
    lint:
      run: bun biome lint --config-path=.biome.jsonc --no-errors-on-unmatched
    lint-sol:
      glob: 'contracts/**/*\.sol'
      run: bun solhint --config contracts/.solhint.json {staged_files}
